name: spreadsheet_decoder
description: A lightweight library for parsing and updating spreadsheet documents
version: 2.3.0
homepage: https://github.com/sestegra/spreadsheet

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  archive: ^4.0.2
  xml: ^6.5.0

dev_dependencies:
  path: ^1.9.0
  lints: ^5.0.0
  test: ^1.25.8
